# Generated by Django 4.0.1 on 2022-01-15 12:18

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[core.validators.validate_title])),
                ('isbn_13', models.CharField(max_length=13, validators=[core.validators.validate_isbn13])),
                ('cover_link', models.TextField(validators=[core.validators.validate_cover_link])),
                ('pages_count', models.IntegerField(validators=[core.validators.validate_pages_count])),
                ('publication_language', models.CharField(max_length=2, validators=[core.validators.validate_pub_lang])),
                ('publication_date', models.DateField(null=True)),
                ('authors', models.ManyToManyField(to='core.Author')),
            ],
        ),
    ]
