# Generated by Django 4.0.1 on 2022-01-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn_13', models.CharField(max_length=13)),
                ('cover_link', models.TextField()),
                ('liczba_stron', models.IntegerField()),
                ('publication_language', models.CharField(max_length=2)),
                ('authors', models.ManyToManyField(to='core.Author')),
            ],
        ),
    ]
