# Generated by Django 4.0.1 on 2022-01-13 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='liczba_stron',
            new_name='pages_count',
        ),
    ]
