# Generated by Django 4.0.1 on 2022-01-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_liczba_stron_book_pages_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(to='core.Book'),
        ),
    ]
