# Generated by Django 4.0.1 on 2022-01-15 14:49

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_published_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.IntegerField(max_length=13, validators=[core.validators.validate_isbn13]),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
