# Generated by Django 4.0.1 on 2022-01-15 14:51

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_book_isbn_13_alter_book_published_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.IntegerField(validators=[core.validators.validate_isbn13]),
        ),
    ]
