# Generated by Django 4.0.1 on 2022-01-16 01:18

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_book_isbn_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.IntegerField(default=0, validators=[core.validators.validate_isbn13]),
        ),
    ]
