# Generated by Django 4.0.1 on 2022-01-16 16:16

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_book_cover_link_alter_book_pages_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.BigIntegerField(default=0, validators=[core.validators.validate_isbn13]),
        ),
    ]
